# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_uparl.ipynb.

# %% auto 0
__all__ = ['Uparl']

# %% ../nbs/10_uparl.ipynb 3
import pandas as pd

# %% ../nbs/10_uparl.ipynb 4
class Uparl:
    def __init__(self, path):
        # self.path = path
        df = pd.read_excel(path)
        self.df = df

    def convert(self):
        print("a")

    @staticmethod
    def covertExcel(path):

        ins = Uparl(path)
        ins.convert()

        
